/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    height: 250,
    width: 592,
    layout: 'absolute',
    title: '模板列',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    x: 20,
                    y: 60,
                    id: 'comboboxTemplateColumn2',
                    maxHeight: 50,
                    width: 470,
                    fieldLabel: '模板列选择',
                    store: 'templateColumnStore',
                    listeners: {
                        beforequery: {
                            fn: me.onComboboxTemplateColumn2BeforeQuery,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'button',
                    x: 520,
                    y: 60,
                    text: '选择',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onComboboxTemplateColumn2BeforeQuery: function(queryPlan, eOpts) {

        var comboboxservice = Ext.getCmp("comboboxTemplateColumn");

        //var name =encodeURIComponent(encodeURIComponent(comboboxservice.getValue()));
        var name =comboboxservice.getValue();

        //alert(name);
        if (serviceid === ""||!serviceid) {
            return;
        }

        comboboxservice.store.loadPage(1);
        comboboxservice.expand();
    },

    onButtonClick: function(button, e, eOpts) {
        var answer =Ext.getCmp('taanswer').getValue();
        alert(answer);

        var columnName = Ext.getCmp("comboboxTemplateColumn").getRawValue();
        alert(columnName);
        answer = answer+"<@"+columnName+">";
        Ext.getCmp('taanswer').setValue(answer);
        win.close();

    }

});