/*
 * File: app/view/MyWindow1.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow1', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.button.Button'
    ],

    height: 449,
    width: 685,
    layout: 'absolute',
    title: '请选择合适词模',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'radiogroup',
                    x: 30,
                    y: 50,
                    height: 350,
                    width: 620,
                    fieldLabel: '词模条目',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'radiofield',
                            boxLabel: 'Box Label'
                        },
                        {
                            xtype: 'radiofield',
                            boxLabel: 'Box Label'
                        }
                    ],
                    listeners: {
                        beforerender: {
                            fn: me.onRadiogroupBeforeRender,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'button',
                    x: 520,
                    y: 10,
                    width: 60,
                    text: '确认',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'button',
                    x: 600,
                    y: 10,
                    width: 60,
                    text: '取消',
                    listeners: {
                        click: {
                            fn: me.onButtonClick1,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onRadiogroupBeforeRender: function(component, eOpts) {

    },

    onButtonClick: function(button, e, eOpts) {

    },

    onButtonClick1: function(button, e, eOpts) {

    }

});