/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.RadioGroup',
        'Ext.button.Button'
    ],

    height: 283,
    width: 526,
    layout: 'absolute',
    title: '请您选择后续节点',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'radiogroup',
                    x: 10,
                    y: 50,
                    height: 150,
                    id: 'nextabs',
                    style: 'margin-left:10px',
                    width: 490,
                    autoScroll: true,
                    fieldLabel: '节点名称',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    listeners: {
                        beforerender: {
                            fn: me.onRadiogroupBeforeRender,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'button',
                    x: 430,
                    y: 220,
                    id: 'ok',
                    width: 60,
                    text: '确定'
                },
                {
                    xtype: 'button',
                    x: 350,
                    y: 220,
                    width: 60,
                    text: '取消'
                }
            ]
        });

        me.callParent(arguments);
    },

    onRadiogroupBeforeRender: function(component, eOpts) {

    }

});