/*
 * File: app/model/faqModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.faqModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'answer',
            type: 'string'
        },
        {
            name: 'channel',
            type: 'string'
        },
        {
            name: 'answertype',
            type: 'string'
        },
        {
            name: 'starttime',
            type: 'string'
        },
        {
            name: 'endtime',
            type: 'string'
        },
        {
            name: 'kbanswerid',
            type: 'string'
        },
        {
            name: 'kbcontentid',
            type: 'string'
        },
        {
            name: 'kbansvaliddateid',
            type: 'string'
        },
        {
            name: 'customertype',
            type: 'string'
        },
        {
            name: 'servicetype',
            type: 'string'
        }
    ]
});