/*
 * File: app/model/ModelGridPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.ModelGridPanel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'id',
            type: 'string'
        },
        {
            name: 'wordpat',
            type: 'string'
        },
        {
            name: 'city',
            type: 'string'
        },
        {
            name: 'correctratio',
            type: 'string'
        },
        {
            name: 'callnumber',
            type: 'string'
        },
        {
            name: 'autosendswitch',
            type: 'string'
        },
        {
            name: 'number',
            type: 'string'
        },
        {
            name: 'wordpatid',
            type: 'string'
        },
        {
            name: 'simplewordpat',
            type: 'string'
        },
        {
            name: 'issequence',
            type: 'string'
        },
        {
            name: 'returnvalues',
            type: 'string'
        },
        {
            name: 'wordpattypename',
            type: 'string'
        }
    ]
});