/*
 * File: app/store/templateColumnStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.templateColumnStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.templateColumnModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'MyApp.model.templateColumnModel',
            storeId: 'templateColumnStore',
            proxy: {
                type: 'ajax',
                url: '../templateColumnForDDL.action',
                reader: {
                    type: 'json',
                    root: 'users'
                }
            },
            listeners: {
                load: {
                    fn: me.onJsonstoreLoad,
                    scope: me
                },
                beforeload: {
                    fn: me.onJsonstoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreLoad: function(store, records, successful, eOpts) {
        // var ddl=Ext.getCmp('comboboxTemplateColumn');//不能删
        // //alert("节点"+ ddl);
        // if(records.length==0){
        //     ddl.setValue(ddl.getValue());
        // }
    },

    onJsonstoreBeforeLoad: function(store, operation, eOpts) {

        var comboboxTemplateColumn = Ext.getCmp('comboboxTemplateColumn');
        var templateColumnName = comboboxTemplateColumn.getValue();

        //templateColumnName =encodeURIComponent(templateColumnName);
        //servicepart=servicepart.replace(/\+/g,"%2B");
        // if(templateColumnName===""||!templateColumnName){
        //     return;
        // }

        //templateColumnName =encodeURIComponent(templateColumnName);
        //alert(templateColumnName);
        this.proxy.extraParams = { name: templateColumnName,serviceid:serviceid,type:'selectTemplateColumn' };
    }

});