package com.knowology.km.UIAOInterfaceWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "FindAnswerWSDelegate", targetNamespace = "http://Services.UIAOInterfaceWebService.knowology.com/")
public interface FindAnswerWSDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "FindAnswer")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "FindAnswer", targetNamespace = "http://Services.UIAOInterfaceWebService.knowology.com/", className = "com.knowology.km.UIAOInterfaceWS.FindAnswer")
	@ResponseWrapper(localName = "FindAnswerResponse", targetNamespace = "http://Services.UIAOInterfaceWebService.knowology.com/", className = "com.knowology.km.UIAOInterfaceWS.FindAnswerResponse")
	public String findAnswer(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "NLPAnalyze")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "NLPAnalyze", targetNamespace = "http://Services.UIAOInterfaceWebService.knowology.com/", className = "com.knowology.km.UIAOInterfaceWS.NLPAnalyze")
	@ResponseWrapper(localName = "NLPAnalyzeResponse", targetNamespace = "http://Services.UIAOInterfaceWebService.knowology.com/", className = "com.knowology.km.UIAOInterfaceWS.NLPAnalyzeResponse")
	public String nlpAnalyze(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
